window.TransforkNew.LOAD.defineManager({
    id: "TOOLS",
    stations: [
        { file: "TOOLS/state.js" },
        { file: "TOOLS/activate.js" },
        { file: "TOOLS/line.js" },
        { file: "TOOLS/MOVE/state.js" },
        { file: "TOOLS/MOVE/01_begin.js" },
        { file: "TOOLS/MOVE/02_capture.js" },
        { file: "TOOLS/MOVE/03_simulation.js" },
        { file: "TOOLS/MOVE/04_transform.js" },
        { file: "TOOLS/MOVE/05_commit.js" },
        { file: "TOOLS/MOVE/interrupts/cancel.js" },
        { file: "TOOLS/ROTATE/state.js" },
        { file: "TOOLS/ROTATE/01_begin.js" },
        { file: "TOOLS/ROTATE/02_capture.js" },
        { file: "TOOLS/ROTATE/03_simulation.js" },
        { file: "TOOLS/ROTATE/04_transform.js" },
        { file: "TOOLS/ROTATE/05_commit.js" },
        { file: "TOOLS/ROTATE/interrupts/cancel.js" },
        { file: "TOOLS/SCALE/state.js" },
        { file: "TOOLS/SCALE/01_begin.js" },
        { file: "TOOLS/SCALE/02_capture.js" },
        { file: "TOOLS/SCALE/03_simulation.js" },
        { file: "TOOLS/SCALE/04_transform.js" },
        { file: "TOOLS/SCALE/05_commit.js" },
        { file: "TOOLS/SCALE/interrupts/cancel.js" },
        { file: "TOOLS/FLIP/flipHorizontal.js" },
        { file: "TOOLS/FLIP/flipVertical.js" },
        { file: "REFRESH/state.js" },
        { file: "REFRESH/01_boundingBox.js" },
        { file: "REFRESH/02_buttons.js" },
        { file: "REFRESH/03_overlay.js" },
        { file: "REFRESH/run.js" },
        { file: "TOOLS/factoryLine.js" },
        { file: "UTILS/coords.js" },
        { file: "UTILS/COORDS/boundsToScreenRect.js" }
    ]
});
