window.TransforkNew.LOAD.defineManager({
    id: "BUTTONS",
    stations: [
        { file: "UI/ELEMENTS/buttons.js" },
        { file: "UI/ELEMENTS/BUTTONS/rotateButton.js" },
        { file: "UI/ELEMENTS/BUTTONS/ROTATEBUTTON/draw.js" },
        { file: "UI/ELEMENTS/BUTTONS/ROTATEBUTTON/mouseDown.js" },
        { file: "UI/ELEMENTS/BUTTONS/ROTATEBUTTON/mouseMove.js" },
        { file: "UI/ELEMENTS/BUTTONS/ROTATEBUTTON/mouseUp.js" },
        { manager: "SCALEBUTTON" },
        { manager: "MOVEBUTTON" },
        { file: "UI/ELEMENTS/BUTTONS/flipHButton.js" },
        { file: "UI/ELEMENTS/BUTTONS/FLIPHBUTTON/draw.js" },
        { file: "UI/ELEMENTS/BUTTONS/FLIPHBUTTON/click.js" },
        { file: "UI/ELEMENTS/BUTTONS/flipVButton.js" },
        { file: "UI/ELEMENTS/BUTTONS/FLIPVBUTTON/draw.js" },
        { file: "UI/ELEMENTS/BUTTONS/FLIPVBUTTON/click.js" },
        { file: "UI/ELEMENTS/BUTTONS/resetTransformButton.js" },
        { file: "UI/ELEMENTS/BUTTONS/CLEARBUTTON/draw.js" },
        { file: "UI/ELEMENTS/BUTTONS/CLEARBUTTON/click.js" },
        { file: "UI/ELEMENTS/BUTTONS/transparencyButton.js" },
        { file: "UI/ELEMENTS/BUTTONS/TRANSPARENCYBUTTON/draw.js" },
        { file: "UI/ELEMENTS/BUTTONS/sizeWButton.js" },
        { file: "UI/ELEMENTS/BUTTONS/SIZEWBUTTON/draw.js" },
        { file: "UI/ELEMENTS/BUTTONS/SIZEWBUTTON/mouseDown.js" },
        { file: "UI/ELEMENTS/BUTTONS/SIZEWBUTTON/mouseMove.js" },
        { file: "UI/ELEMENTS/BUTTONS/SIZEWBUTTON/mouseUp.js" },
        { file: "UI/ELEMENTS/BUTTONS/sizeHButton.js" },
        { file: "UI/ELEMENTS/BUTTONS/SIZEHBUTTON/draw.js" },
        { file: "UI/ELEMENTS/BUTTONS/SIZEHBUTTON/mouseDown.js" },
        { file: "UI/ELEMENTS/BUTTONS/SIZEHBUTTON/mouseMove.js" },
        { file: "UI/ELEMENTS/BUTTONS/SIZEHBUTTON/mouseUp.js" }
    ]
});
